language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.8.0-cp36-cp36m-linux_x86_64.whl

script:
  - pytest --cov=gameframework .
  
after_success:
  - coveralls
